### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by davidray** [kofno/ajaxian#3]
The example on the readme doesn't work. Providing a string as a method results in a type error. 😭 

`const url =
      "https://trooptrack.com/api/v1/events?start_on=20160101&end_on=20170501";

    const request = {
      url: url,
      method: "get",
      data: "",
      timeout: 0,
      headers: [
        ["X-User-Token", "Z_XlCRvYGhM28Eds4zW1RA"],
        ["X-Partner-Token", "6ERQj94v4k9_VAc0_Spz8A"],
      ],
      withCredentials: false,
      decoder: () => ok({}),
    };`

`Argument of type '{ url: string; method: string; data: string; timeout: number; headers: string[][]; withCredential...' is not assignable to parameter of type 'Request<{}>'.
  Types of property 'method' are incompatible.
    Type 'string' is not assignable to type 'Method'.`

Or maybe the type Method is not right?

**Comment by kofno** [comment]
You need to be more explicit in this case by telling TS that request is an Request type:

```
const request: Request<{}> = {
  url: url,
  method: "get",
  data: "",
  timeout: 0,
  headers: [
    ["X-User-Token", "Z_XlCRvYGhM28Eds4zW1RA"],
    ["X-Partner-Token", "6ERQj94v4k9_VAc0_Spz8A"],
  ],
  withCredentials: false,
  decoder: () => ok({}),
};`
```
^ that should fix it.

You can see a full example here --> https://github.com/kofno/ajaxian/tree/master/examples/get-request
